# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_app', '0002_auto_20160804_1010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='expdata',
            unique_together=set([('braf', 'brap', 'brca1', 'brca2', 'brcc3', 'brd1', 'brd2', 'brd3', 'brd4', 'patient')]),
        ),
    ]
